services:
  blink-api:
    build: .
    container_name: blink-api
    restart: unless-stopped
    env_file: .env
    environment:
      - TZ=America/New_York
    volumes:
      # Credentials file
      - ./credentials.json:/app/credentials.json
      # Directory where downloaded media will be saved
      - /mnt/plex/media/blink:/app/media
    ports:
      - "5001:5001"
